# Site settings
baseurl = "http://example.org/"
languageCode = "he-IL"
title = "Pogim"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "פוגים"
    subtitle = ""
    author = "אמיר גרוצקי"
    description = ""
    keywords = "פוגים, פוג"

    # Footer text
    footertext = " נבנה על-ידי [אמיר גרוצקי](https://github.com/GeReV) &middot; תוכן האתר מוגש בכפוף לרישיון [Creative Commons BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
