# Site settings
baseurl = "http://example.org/"
languageCode = "he-IL"
title = "Pogim"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "פוגים"
    subtitle = ""
    author = "אמיר גרוצקי"
    description = ""
    keywords = "פוגים, פוג"

    # Footer text
    footertext = "כל הזכויות שמורות ל[אמיר גרוצקי](https://github.com/gerev), משהו על רישיון"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
