const SERIES_CONVERSION = {
  green: 'הסדרה הירוקה',
  red: 'הסדרה האדומה',
  blue: 'הסדרה הכחולה',
  purple: 'הסדרה הסגולה',
  orange: 'הסדרה הכתומה',
  pink: 'הסדרה הורודה',
  poalim: 'בנק פועלים',
  brown: 'הסדרה החומה',
  black: 'הסדרה השחורה (סונול)',
  gray: 'הסדרה האפורה',
  turquoise: 'סדרת הטורקיז',
  psycho: 'פסיכי בריבוע',
  'psycho-blue-white': 'פסיכי בריבוע',
  gold: 'סדרת הזהב (באדי תנובה)',
  dominos: 'הסדרה האמריקאית (דומינו\'ס פיצה)',
  'comedy-store': 'הקומדי סטור',
  'comedy-store-yellow': 'הקומדי סטור (סדרה צהובה)',
  crazies: 'סדרת המוטרפים',
  'bushido-green': 'ענקי הבושידו',
  'bushido-purple': 'ענקי הבושידו',
  yellow: 'הסדרה הצהובה',
  horospog: 'הורוספוג',
  hologram: 'סדרת היקרים',
};

export default SERIES_CONVERSION;
